// Mocks generated by Mockito 5.4.2 from annotations
// in wordsapp/test/features/signIn/respository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wordsapp/core/api/api_response.dart' as _i2;
import 'package:wordsapp/features/signIn/data/models/sign_in_response_model.dart'
    as _i5;
import 'package:wordsapp/features/signIn/data/repositories/sign_in_repository_impl.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<Data> extends _i1.SmartFake
    implements _i2.ApiResponse<Data> {
  _FakeApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SignInRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInRepositoryImpl extends _i1.Mock
    implements _i3.SignInRepositoryImpl {
  @override
  _i4.Future<_i2.ApiResponse<_i5.SignInResponseModel>> authenticate(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<_i5.SignInResponseModel>>.value(
            _FakeApiResponse_0<_i5.SignInResponseModel>(
          this,
          Invocation.method(
            #authenticate,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ApiResponse<_i5.SignInResponseModel>>.value(
                _FakeApiResponse_0<_i5.SignInResponseModel>(
          this,
          Invocation.method(
            #authenticate,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<_i5.SignInResponseModel>>);
}
