name: wordsapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_tts: ^3.7.0
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  flutter_localization: ^0.1.13
  intl: ^0.18.1
  localization: ^2.1.0
  bloc: ^8.1.2
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  connectivity_plus: ^4.0.2
  safe_device: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.2
  test: ^1.24.3

flutter:
  uses-material-design: true
  generate: true